### PR TITLE
Update 2019-02-06-php-jit.md

### PR DESCRIPTION
**Pull request by techbio**
image --> imagine
:)

### CODE REVIEW

**Comment by brendt** [comment]
Can you remove the elephpant change though? :)

**Comment by techbio** [comment]
Done. I wasn't quite sure about that one, but now I know. Great blog, thanks.

**Review by techbio — COMMENTED** [review]
Reverted elephant --> elephpant
(I see, elePHPant :)

**Comment by brendt** [comment]
Thanks!

**Pull request merged**
