### PR TITLE
Add `static` modifier to example.

### PR DESCRIPTION
**Pull request by andersonamuller**

### CODE REVIEW

**Comment by brendt** [comment]
How come? It's supposed to be non static

**Comment by andersonamuller** [comment]
This example was under this sentence:

> Static methods are allowed as well. Also note that you can use `self` within an enum:

So I though you meant to show show that would look like. But I realize the rest of the example doesn't make sense then.

**Comment by brendt** [comment]
I see, I'll try to rephrase that, thanks for pointing out!

**Comment by andersonamuller** [comment]
You'r welcome, thank you for the nice posts you write!

**Pull request closed without merging**
