### PR TITLE
Small improvements to chapter 2

### PR DESCRIPTION
**Pull request by drbyte**
Small improvements

### CODE REVIEW

**Comment by drbyte** [comment]
Oops - apologies if the "next week" change is premature. I saw that the Actions file existed in VCS, but only later realized it's not released on the blog yet.

**Comment by brendt** [comment]
Yeah, you're one of the few people who was able to already read the next chapter :D Could you remove that change?

**Comment by brendt** [comment]
I could of course fix it myself. Thanks again!

**Comment by drbyte** [comment]
Hey! now that's rare to get an all-digits hash on your commit!
Screen Shot 2019-10-22 at 1 22 12 PM

**Comment by brendt** [comment]
Pretty cool indeed!

**Pull request merged**
